Part 5 refactor
SamanAtashi/School_Library pull request #5
Opened 2021-12-21 09:24 UTC by SamanAtashi

# OOP school library: refactor your code
Features introduced are as follow:

- Describe the SOLID principles of OOP.
- Refactor your own Ruby code after gaining new knowledge.
- Apply Ruby best practices and language style guides in code.

2021-12-21 10:58 UTC, mikethreels requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 10:58 UTC, mikethreels commented on bin/methods/create_a_book.rb
> +  end
- [ ] good job cleaning up the main.rb file 👍 in this method text is printed in the console, information is gathered and it is processed, this is not in line with the single responsibility principle, try to split this into smaller methods with a single responsibility. for more details have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

2021-12-21 10:58 UTC, mikethreels commented on bin/methods/create_a_rental.rb
> +  end
- [ ] good job cleaning up the main.rb file 👍 in this method text is printed in the console, information is gathered and it is processed, this is not in line with the single responsibility principle, try to split this into smaller methods with a single responsibility. for more details have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

2021-12-21 10:58 UTC, mikethreels commented on bin/methods/create_a_student.rb
> +  end
- [ ] good job cleaning up the main.rb file 👍 in this method text is printed in the console, information is gathered and it is processed, this is not in line with the single responsibility principle, try to split this into smaller methods with a single responsibility. for more details have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

2021-12-21 10:58 UTC, mikethreels commented on bin/methods/create_a_teacher.rb
> +  end
- [ ] good job cleaning up the main.rb file 👍 in this method text is printed in the console, information is gathered and it is processed, this is not in line with the single responsibility principle, try to split this into smaller methods with a single responsibility. for more details have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

2021-12-22 08:35 UTC, dasileker approved these changes
## **Hi @SamanAtashi,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 

### **optional**

- Please remove the disabled rubocop linters and try to solve the issue.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 08:57 UTC, merged